<template>
  <div class="navbar bg-base-200 z-10 justify-between">
    <div class="btn btn-ghost text-2xl font-bold">Personal Resume</div>
    <div class="flex gap-2">
      <a
        href="https://github.com/NTPLSRPP"
        target="_blank"
        class="btn"
      >
        <v-icon name="co-github" class="scale-[2]" />
      </a>
      <a
        href="https://www.linkedin.com/in/nathaphat-lertsiriphongphan-92982227a/"
        target="_blank"
        class="btn"
      >
        <v-icon name="co-linkedin" class="scale-[2]" />
      </a>
      <a
        href="https://www.instagram.com/ntplsrpp_/"
        target="_blank"
        class="btn"
      >
        <v-icon name="co-instagram" class="scale-[2]" />
      </a>
      <button class="btn btn-ghost" @click="ChangeTheme()">
        <v-icon v-if="isDark" name="co-moon" class="scale-[2]" />
        <v-icon v-else name="co-sun" class="scale-[2]" />
      </button>
    </div>
  </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
const emit = defineEmits(["theme"]);
const isDark = ref(true);
const ChangeTheme = () => {
  emit("theme");
  isDark.value = !isDark.value;
};
onMounted(() => {
  if (localStorage.getItem("theme") !== "dark") {
    isDark.value = false;
  }
});
</script>

<style lang="css" scoped>
a :hover{
  -webkit-animation: color-change-3x 2s linear infinite alternate both;
	        animation: color-change-3x 2s linear infinite alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-8-28 3:17:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-3x
 * ----------------------------------------
 */
 @-webkit-keyframes color-change-3x {
  0% {
    color: #19dcea;
  }
  50% {
    color: #b22cff;
  }
  100% {
    color: #ea2222;
  }
}
@keyframes color-change-3x {
  0% {
    color: #19dcea;
  }
  50% {
    color: #b22cff;
  }
  100% {
    color: #ea2222;
  }
}

</style>
