<template>
  <div id="main" :data-theme="theme" class="h-screen overflow-y-scroll bg-base-300 overflow-x-hidden">
    <navBar class="fixed top-0" @theme="toggleTheme()"></navBar>
    <tab @activeTab="activeTab"></tab>
    <mainView :class="sliceLeft ? 'slide-in-right' : 'slide-in-left'" v-show="tabActive === 1"></mainView>
    <mainView2 :class="sliceLeft ? 'slide-in-right' : 'slide-in-left'" v-show="tabActive === 2" ></mainView2>
    <mainView3 :class="sliceLeft ? 'slide-in-right' : 'slide-in-left'" v-show="tabActive === 3"></mainView3>
  </div>
</template>

<script setup>
import navBar from '@/components/navbar.vue'
import mainView from '@/components/mainView.vue'
import mainView2 from './components/mainView2.vue'
import mainView3 from './components/mainView3.vue'
import { ref, onMounted } from 'vue'
import tab from '@/components/tab.vue'

const tabActive = ref(1)
const sliceLeft = ref(true)
const theme = ref('dark') // Initialize with a default theme

onMounted(() => {
  theme.value = localStorage.getItem('theme') || 'dark'
})

const toggleTheme = () => {
  theme.value = theme.value === 'dark' ? 'garden' : 'dark'
  localStorage.setItem('theme', theme.value)
}

const activeTab = (numTab) => {
  if (numTab > tabActive.value) {
    sliceLeft.value = true
  } else {
    sliceLeft.value = false
  }
  tabActive.value = numTab
}
</script>

<style lang="css" scoped>
#main {
  scrollbar-width: none;
}

.slide-in-right {
	-webkit-animation: slide-in-right 0.5s ease-in-out both;
	        animation: slide-in-right 0.5s ease-in-out both;
}
.slide-out-right {
	-webkit-animation: slide-out-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: slide-out-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
.slide-in-left {
	-webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
.slide-out-left {
	-webkit-animation: slide-out-left 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: slide-out-left 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2024-8-28 2:30:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2024-8-28 2:44:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-right
 * ----------------------------------------
 */
 @-webkit-keyframes slide-out-right {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
}
@keyframes slide-out-right {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-8-28 2:40:43
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2024-8-28 2:44:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-left
 * ----------------------------------------
 */
 @-webkit-keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
}
@keyframes slide-out-left {
  0% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
}

</style>